// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Fluent Project Contributors
/**
 * Generates `src/environments/environment.local.ts` and
 * `src/environments/environment.prod.ts` from a `.env` file at repo root.
 *
 * Why a dedicated script instead of dotenv at runtime: Angular's `ng build`
 * inlines environment values at compile time via `fileReplacements`. So we
 * materialize TS files from `.env` *before* invoking the Angular CLI.
 *
 * Usage:
 *   npm run setup:env                 # generates both local + prod variants
 *   USE_EMULATORS=true npm run setup:env
 *
 * In CI: populate env vars from your secret manager, then run this script
 * before `ng build --configuration=production`.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const ENV_FILE = join(ROOT, '.env');
const TARGET_LOCAL = join(ROOT, 'src/environments/environment.local.ts');
const TARGET_PROD = join(ROOT, 'src/environments/environment.prod.ts');

/** Naive .env parser; intentionally avoids the `dotenv` dep. */
function loadDotenv(path) {
  if (!existsSync(path)) return {};
  const out = {};
  for (const raw of readFileSync(path, 'utf8').split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

const fromFile = loadDotenv(ENV_FILE);
const env = { ...fromFile, ...process.env };

const REQUIRED = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_SENDER_ID',
  'FIREBASE_APP_ID',
  'GOOGLE_MAPS_API_KEY',
  'GOOGLE_MAPS_MAP_ID',
  'APP_CHECK_SITE_KEY',
];

const missing = REQUIRED.filter((k) => !env[k]);
if (missing.length) {
  console.warn(
    '[setup:env] Missing keys (will use placeholders): ' + missing.join(', ')
  );
  console.warn('[setup:env] Copy .env.example to .env and fill in real values.');
}

function pick(key, fallback = '') {
  return env[key] && env[key].length > 0 ? env[key] : fallback;
}

function render(production) {
  return `// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Fluent Project Contributors
//
// AUTOGENERATED by scripts/setup-env.mjs from .env. Do not edit by hand.
// This file is gitignored. Re-run \`npm run setup:env\` to regenerate.

import type { FluentEnvironment } from './types';

export const environment: FluentEnvironment = {
  production: ${production},
  emulators: ${pick('USE_EMULATORS', 'false') === 'true' && !production},
  firebase: {
    apiKey: ${JSON.stringify(pick('FIREBASE_API_KEY'))},
    authDomain: ${JSON.stringify(pick('FIREBASE_AUTH_DOMAIN'))},
    projectId: ${JSON.stringify(pick('FIREBASE_PROJECT_ID'))},
    storageBucket: ${JSON.stringify(pick('FIREBASE_STORAGE_BUCKET'))},
    messagingSenderId: ${JSON.stringify(pick('FIREBASE_SENDER_ID'))},
    appId: ${JSON.stringify(pick('FIREBASE_APP_ID'))},
    measurementId: ${JSON.stringify(pick('FIREBASE_MEASUREMENT_ID'))},
  },
  googleMapsApiKey: ${JSON.stringify(pick('GOOGLE_MAPS_API_KEY'))},
  googleMapsMapId: ${JSON.stringify(pick('GOOGLE_MAPS_MAP_ID', 'DEMO_MAP_ID'))},
  appCheckSiteKey: ${JSON.stringify(pick('APP_CHECK_SITE_KEY'))},
  region: ${JSON.stringify(pick('GCP_REGION', 'us-central1'))},
};
`;
}

writeFileSync(TARGET_LOCAL, render(false));
writeFileSync(TARGET_PROD, render(true));
console.log('[setup:env] Wrote', TARGET_LOCAL);
console.log('[setup:env] Wrote', TARGET_PROD);
